### ISSUE TITLE
Changes not pulled from our repo

### ISSUE THREAD

**Issue by duner** [Medill/TheFlux#15]
This commit from last night with some final copy updates isn't on the site for some reason: https://github.com/SarahTurbin/TheFlux/commit/c901824230dd58dd9b5caafb11431d7a86ce97fc

We also made a bug fix this morning https://github.com/SarahTurbin/TheFlux/commit/58036b3c6dba4fa420a59e15715ed63aba82f2b8 to our repo which would be great if it could be pulled into the main site.

**Comment by zachwise** [comment]
Can you do a pull request?

**Comment by duner** [comment]
@zachwise: Can I get push rights?

```
ERROR: Permission to Medill/TheFlux.git denied to duner.
fatal: Could not read from remote repository.
```

**Comment by zachwise** [comment]
I gave it to you, but you need to accept the invite

**Comment by duner** [comment]
I think this is fixed in 40ef62035ed2f911968193518d7c5dbe2c40045d. @zachwise, I'm not seeing the changes on the live site—is that something on your end?

**Comment by zachwise** [comment]
Live changes will be pushed later. We're debugging in master

**Comment by duner** [comment]
Great. I'm going to close this then. Thanks for the help.
